import { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = "https://drerkanelci.com";

  const routes = [
    "",
    "/hakkimda",
    "/iletisim",
    "/videolar",
    "/robotik-cerrahi",
    "/kisirlik-tedavisi",
    "/yuksek-riskli-gebelikler",
    "/ileri-laparoskopik-cerrahi",
    "/histeroskopik-cerrahi",
    "/gebelik-dogum",
    "/jinekoloji",
    "/urojinekoloji",
    "/vnotes",
    "/endometriozis",
    "/endometriozis/belirtileri-tedavi",
    "/endometriozis/bas-etme-yollari",
    "/endometriozis/cikolata-kisti",
    "/miyom",
    "/miyom/miyom-nedir",
    "/miyom/izsiz-miyom-ameliyati",
    "/miyom/vajinal-miyom-ameliyati",
    "/miyom/dikissiz-miyom-ameliyati",
    "/miyom/vnotes-miyom-ameliyati",
    "/miyom/rahim-koruyucu-miyom-ameliyati",
    "/miyom/rahim-alinmadan-miyom-ameliyati",
    "/miyom/kapali-miyom-ameliyati",
    "/miyom/rahim-cikartmadan-miyom-ameliyati",
    "/miyom/sikca-sorulan-sorular",
    "/genital-estetik",
    "/genital-estetik/labioplasti",
    "/genital-estetik/vajinal-daraltma",
    "/genital-estetik/klitoris-estetigi",
    "/genital-estetik/monsplasti",
    "/genital-estetik/perinoplasti",
    "/genital-estetik/barbieplasti",
    "/genital-estetik/kok-hucre-eksosom",
    "/genital-estetik/prp-mezoterapi",
    "/genital-estetik/yag-injeksiyonu",
    "/genital-estetik/orgazm-asisi",
    "/genital-estetik/genital-estetik-labioplasti",
    "/genital-estetik/dogal-genital-estetik",
    "/genital-estetik/revizyon-genital-estetik",
    "/genital-estetik/barbie-genital-estetik",
    "/genital-estetik/barbie-vajina-estetigi",
    "/hpv-kolposkopi",
    "/hpv-kolposkopi/hpv-nedir",
    "/hpv-kolposkopi/hpv-iliskili-hastaliklar",
    "/hpv-kolposkopi/hpv-asilamasi",
    "/hpv-kolposkopi/kolposkopi-nedir",
    "/hpv-kolposkopi/pap-smear",
    "/hpv-kolposkopi/ascus",
    "/hpv-kolposkopi/asc-h",
    "/hpv-kolposkopi/lsil",
    "/hpv-kolposkopi/hsil",
    "/hpv-kolposkopi/cin-siniflandirmasi",
    "/hpv-kolposkopi/cin-lazer-tedavisi",
    "/hpv-kolposkopi/leep-ameliyati",
    "/hpv-kolposkopi/konizasyon",
    "/hpv-kolposkopi/genital-sigil",
    "/hpv-kolposkopi/genital-sigil-tedavisi",
    "/hpv-kolposkopi/gebelerde-genital-sigil",
    "/hpv-kolposkopi/bitkisel-tedaviler",
    "/jinekolojik-onkoloji",
    "/jinekolojik-onkoloji/rahim-agzi-kanseri",
    "/jinekolojik-onkoloji/rahim-kanseri",
    "/jinekolojik-onkoloji/yumurtalik-kanseri",
    "/jinekolojik-onkoloji/vulva-kanseri",
    "/jinekolojik-onkoloji/vajina-kanseri",
    "/jinekolojik-onkoloji/tup-kanseri",
    "/jinekolojik-onkoloji/periton-kanseri",
    "/jinekolojik-onkoloji/rahim-sarkomu",
    "/jinekolojik-onkoloji/hpv-asilamasi",
    "/jinekolojik-onkoloji/hipec",
    "/jinekolojik-onkoloji/metastatik-kanser",
    "/jinekolojik-onkoloji/trofoblastik-tumorler",
    "/jinekolojik-onkoloji/nuks-kanser",
    "/jinekolojik-onkoloji/meme-kanseri-taramasi",
  ];

  return routes.map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date(),
    changeFrequency: route === "" ? "weekly" : "monthly",
    priority: route === "" ? 1 : route.includes("/") && route.split("/").length > 2 ? 0.6 : 0.8,
  }));
}
